[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bnnp"
version = "0.1"
dependencies = [
    "pytest",
    "torch",
]

[tool.ruff]
line-length = 88
exclude = ["data", "runs"]

[tool.setuptools]
packages = ["bnnp", "bnnp.nn", "bnnp.distmuon"]
